replicaCount: 2

image:
  repository: "<account-id>.dkr.ecr.us-west-2.amazonaws.com/lesson-5-app"
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

livenessProbe:
  httpGet:
    path: /health/live/
    port: 8000
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health/ready/
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

monitoring:
  enabled: true
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics/"

config:
  env:
    DJANGO_SECRET_KEY: "###"
    DJANGO_DEBUG: "False"
    ALLOWED_HOSTS: "*"
    DATABASE_URL: "postgresql://dbadmin:password@###:5432/djangodb"
