replicaCount: 2

image:
  repository: "<account-id>.dkr.ecr.us-west-2.amazonaws.com/lesson-5-app"
  tag: "latest"
  pullPolicy: IfNotPresent

containerPort: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  env:
    DJANGO_SECRET_KEY: "replace-me"
    DJANGO_DEBUG: "False"
    ALLOWED_HOSTS: "*"
    DATABASE_URL: "postgres://user:password@db:5432/app"
